### ISSUE TITLE
`nfolds` is kwarg of both `prepare_XY` and `k_fold_cross_val` which can cause problems

### ISSUE THREAD

**Issue by georgemilosh** [georgemilosh/Climate-Learning#46]
Also 'u' is multiply defined in the `config.json`

**Comment by AlessandroLovo** [comment]
Yes, this is not a problem if you use `ut.extract_nested` and `ut.set_values_recursive`

**Comment by AlessandroLovo** [comment]
I'll put it as a wontfix for now
