### ISSUE TITLE
Data not normalized prior to being fed into the model when computing Y_pred_unbiased?

### ISSUE THREAD

**Issue by georgemilosh** [georgemilosh/Climate-Learning#58]
https://github.com/georgemilosh/Climate-Learning/blob/b0e5fb354039035aa83a00c3308430ce57882319/PLASIM/Learn2_new.py#L2211

**Comment by georgemilosh** [comment]
For the context the point is that `X_va` needs to be first passed through the function `normalize_X()` because that's how we train the neural network. This should happen after k-fold cross validation split originating from `X`

**Comment by AlessandroLovo** [comment]
I did a few other fixes like when `collective = True`.
However what was wrong with just `X_va = (X_va - X_mean)/X_std` ?
Also maybe we should add some fail-safes in normalize_X so it doesn't accidentally recompute mean and std but rather raises an error

**Comment by georgemilosh** [comment]
The issue was that X_va was not recomputed there. So maybe you should check that you didn't use somewhere those results. Yeah some error message could be useful though it could break the flow of computation

**Comment by AlessandroLovo** [comment]
I always used `collective=False` so no problems on my side.

**Comment by georgemilosh** [comment]
Ok, I have addressed the issue
