### ISSUE TITLE
CESM France mask could be better

### ISSUE THREAD

**Issue by AlessandroLovo** [georgemilosh/Climate-Learning#79]
Right now 'France' is defined as the land area inside a square box:

![Figure 9](https://github.com/georgemilosh/Climate-Learning/assets/44053982/9560e8d9-84c4-4d54-a3b1-7571b6d84af1)

However, the higher resolution of CESM makes it rather pointless to keep this box definition.
Using ef.create_mask_xarray it is possible to have a better representation of France, and this is already implemented for ERA5 data.

The modification is then minimal, but it can be BREAKING for previous work on CESM data

**Comment by AlessandroLovo** [comment]
The new France looks like this:
![Figure 8](https://github.com/georgemilosh/Climate-Learning/assets/44053982/8564fe06-06ae-4b4e-b2ab-1e6b1c67c259)

**Comment by georgemilosh** [comment]
Seems like a minor issue as long as we are not very applied

**Comment by AlessandroLovo** [comment]
Yes, but including the south England part messes up the soil moisture a bit potentially

**Comment by georgemilosh** [comment]
Sure, but it matters that we only include France if this is application study. For me this was a study that compares the models. Original map was not chosen by me. It already had some issues. To be consistent with our [previous literature](https://www.frontiersin.org/articles/10.3389/feart.2023.1235579/full) it is better not to change the area

**Comment by AlessandroLovo** [comment]
Ok, so I'll keep the default as the boxy France, but I'll leave the option to use the more realistic mask

**Comment by AlessandroLovo** [comment]
Now to use xarray mask you explicitly have to provide `area = 'France-xarray'`
